[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]] # colorschema
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]] # slimのハイライト
repo = 'slim-template/vim-slim'

[[plugins]] # HTMLつくーる
repo = 'mattn/emmet-vim'

[[plugins]] # ES6のハイライト
repo = 'othree/yajs.vim'

[[plugins]] # typescriptのハイライト
repo = 'leafgarland/typescript-vim'

[[plugins]] # インデントを見やすく
repo = 'Yggdroot/indentLine'

[[plugins]] # j,kによる移動を爆速に
repo = 'rhysd/accelerated-jk'

[[plugins]] # ステータスバーをかっこよく
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]] # ステータスバーをさらにかっこよく
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ファイルツリー
repo = 'scrooloose/nerdtree'

